//import Navbar from "@/Components/Navbar";
import Navbar from "@/Components/Navbar";
import "../Styles/globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CoderNext",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  //console.log("Hello i am");
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
